# SPDX-License-Identifier: Apache-2.0

"""Drive RolloutController V1 desired state from scaling reports.

Use ``--inject-spike`` for a deterministic 1 -> 2 -> 1 closed-loop check::

    python examples/math/rollout_elastic_autoscaler_spike.py \
        --base-url http://127.0.0.1:PORT --inject-spike --require-proxy

Without ``--inject-spike``, the script polls reports generated by real training
metrics until interrupted::

    python examples/math/rollout_elastic_autoscaler_spike.py \
        --base-url http://127.0.0.1:PORT
"""

from __future__ import annotations

import argparse
import json
import logging
import time
from typing import Any

import requests

from areal.infra.controller.elastic.autoscaler import (
    AutoscalerError,
    ElasticAutoscalerPolicy,
    ScaleDownConfirmation,
)

logger = logging.getLogger("RolloutElasticAutoscalerSpike")


_ScaleDownConfirmation = ScaleDownConfirmation


def _request_json(
    method: str,
    url: str,
    *,
    timeout: float,
    payload: dict[str, Any] | None = None,
) -> dict[str, Any]:
    response = requests.request(method, url, json=payload, timeout=timeout)
    response.raise_for_status()
    result = response.json()
    if not isinstance(result, dict):
        raise AutoscalerError(f"Expected a JSON object from {url}, got {result!r}")
    return result


def _get_status(base_url: str, request_timeout: float) -> dict[str, Any]:
    return _request_json(
        "GET",
        f"{base_url}/elastic/instances",
        timeout=request_timeout,
    )


def _get_recommendation(base_url: str, request_timeout: float) -> dict[str, Any]:
    return _request_json(
        "GET",
        f"{base_url}/elastic/scaling-recommendation",
        timeout=request_timeout,
    )


def _inject_recommendation(
    base_url: str,
    request_timeout: float,
    *,
    entered: int,
    consumed: int,
    wait_seconds: float,
    step_seconds: float,
) -> dict[str, Any]:
    return _request_json(
        "POST",
        f"{base_url}/elastic/scaling-recommendation",
        timeout=request_timeout,
        payload={
            "entered": entered,
            "consumed": consumed,
            "wait_seconds": wait_seconds,
            "step_seconds": step_seconds,
        },
    )


def _set_desired(
    base_url: str,
    request_timeout: float,
    desired_instances: int,
) -> dict[str, Any]:
    return _request_json(
        "PUT",
        f"{base_url}/elastic/desired-instances",
        timeout=request_timeout,
        payload={"desired_instances": desired_instances},
    )


def _validate_stable_status(
    status: dict[str, Any], expected_instances: int, *, require_proxy: bool
) -> tuple[bool, str]:
    reconcile_error = status.get("last_reconcile_error")
    if reconcile_error:
        raise AutoscalerError(f"Controller reconcile failed:\n{reconcile_error}")

    desired = status.get("desired_instances")
    ready = status.get("ready_instances")
    instances = status.get("instances")
    if not isinstance(instances, list):
        raise AutoscalerError(f"Malformed instance status: {status!r}")
    if require_proxy and status.get("proxy_enabled") is not True:
        raise AutoscalerError("Controller has not enabled elastic V1 proxy workers")

    if desired != expected_instances:
        return False, f"desired={desired}"
    if ready != expected_instances or len(instances) != expected_instances:
        return False, f"ready={ready} total={len(instances)}"
    if any(instance.get("state") != "ready" for instance in instances):
        return False, "not all instances are READY"
    if require_proxy and any(not instance.get("proxy_ready") for instance in instances):
        return False, "not all instances have a READY V1 proxy"
    if status.get("pending_update_version") is not None:
        return False, f"pending_version={status['pending_update_version']}"

    serving_version = status.get("serving_version")
    mismatched = [
        instance.get("instance_id")
        for instance in instances
        if instance.get("loaded_version") != serving_version
    ]
    if mismatched:
        return False, (
            f"serving_version={serving_version} mismatched_instances={mismatched}"
        )
    return True, "stable"


def _wait_for_convergence(
    base_url: str,
    *,
    expected_instances: int,
    request_timeout: float,
    convergence_timeout: float,
    poll_interval: float,
    require_proxy: bool,
) -> dict[str, Any]:
    deadline = time.monotonic() + convergence_timeout
    while time.monotonic() < deadline:
        try:
            status = _get_status(base_url, request_timeout)
        except requests.RequestException as exc:
            logger.warning("Status request failed while converging: %s", exc)
            time.sleep(poll_interval)
            continue
        stable, detail = _validate_stable_status(
            status, expected_instances, require_proxy=require_proxy
        )
        logger.info(
            "Waiting for convergence target=%d: %s",
            expected_instances,
            detail,
        )
        if stable:
            return status
        time.sleep(poll_interval)
    raise TimeoutError(
        f"Timed out waiting for {expected_instances} stable READY instances"
    )


def _apply_report(
    base_url: str,
    report: dict[str, Any],
    *,
    request_timeout: float,
    convergence_timeout: float,
    poll_interval: float,
    dry_run: bool,
    require_proxy: bool,
) -> bool:
    if report.get("status") == "empty":
        logger.info("No scaling report is available yet")
        return False

    recommended = report.get("recommended_instances")
    if isinstance(recommended, bool) or not isinstance(recommended, int):
        raise AutoscalerError(f"Malformed scaling report: {report!r}")

    status = _get_status(base_url, request_timeout)
    current_desired = status.get("desired_instances")
    logger.info(
        "Report version=%s branch=%s wait_fraction=%s ready=%s desired=%s "
        "recommended=%s",
        report.get("report_version"),
        report.get("branch"),
        report.get("rollout_wait_fraction"),
        report.get("ready_instances"),
        current_desired,
        recommended,
    )
    if recommended == current_desired:
        logger.info("Desired state already matches the recommendation")
        return False
    if dry_run:
        logger.info("Dry run: would set desired_instances=%d", recommended)
        return False

    response = _set_desired(base_url, request_timeout, recommended)
    logger.info("Set desired state: %s", json.dumps(response, sort_keys=True))
    _wait_for_convergence(
        base_url,
        expected_instances=recommended,
        request_timeout=request_timeout,
        convergence_timeout=convergence_timeout,
        poll_interval=poll_interval,
        require_proxy=require_proxy,
    )
    logger.info("Converged to %d READY instances", recommended)
    return True


def _run_injected_spike(options: argparse.Namespace) -> None:
    scale_down_windows = getattr(options, "scale_down_windows", 2)
    _wait_for_convergence(
        options.base_url,
        expected_instances=1,
        request_timeout=options.request_timeout,
        convergence_timeout=options.convergence_timeout,
        poll_interval=options.poll_interval,
        require_proxy=options.require_proxy,
    )

    logger.info("Injecting scale-up metrics")
    _inject_recommendation(
        options.base_url,
        options.request_timeout,
        entered=20,
        consumed=20,
        wait_seconds=2.0,
        step_seconds=10.0,
    )
    scale_up_report = _get_recommendation(options.base_url, options.request_timeout)
    if scale_up_report.get("branch") != "scale_up":
        raise AutoscalerError(f"Expected a scale_up report, got {scale_up_report!r}")
    _apply_report(
        options.base_url,
        scale_up_report,
        request_timeout=options.request_timeout,
        convergence_timeout=options.convergence_timeout,
        poll_interval=options.poll_interval,
        dry_run=options.dry_run,
        require_proxy=options.require_proxy,
    )
    if options.dry_run:
        return

    confirmation = _ScaleDownConfirmation(scale_down_windows)
    scale_down_report = None
    for _ in range(scale_down_windows):
        logger.info("Injecting scale-down metrics")
        scale_down_report = _inject_recommendation(
            options.base_url,
            options.request_timeout,
            entered=20,
            consumed=5,
            wait_seconds=0.1,
            step_seconds=10.0,
        )
        report_version = int(scale_down_report["report_version"])
        window_start = int(scale_down_report["window_start_version"])
        confirmed, observed = confirmation.observe(
            scale_down_report,
            desired=2,
            window_start=window_start,
            report_version=report_version,
        )
        logger.info(
            "Injected scale-down confirmation window %d/%d",
            observed,
            scale_down_windows,
        )
    if scale_down_report is None or not confirmed:
        raise AutoscalerError("Injected scale-down windows did not confirm scaling")
    _apply_report(
        options.base_url,
        scale_down_report,
        request_timeout=options.request_timeout,
        convergence_timeout=options.convergence_timeout,
        poll_interval=options.poll_interval,
        dry_run=False,
        require_proxy=options.require_proxy,
    )
    logger.info("Closed-loop report -> desired state 1 -> 2 -> 1 spike passed")


def _run_live_loop(options: argparse.Namespace) -> None:
    scale_down_windows = getattr(options, "scale_down_windows", 2)
    policy = ElasticAutoscalerPolicy(
        cooldown_seconds=options.cooldown,
        scale_up_cooldown_seconds=getattr(options, "scale_up_cooldown", 0.0),
        scale_down_cooldown_seconds=getattr(options, "scale_down_cooldown", 30.0),
        direction_change_cooldown_seconds=getattr(
            options, "direction_change_cooldown", 30.0
        ),
        scale_down_windows=scale_down_windows,
    )
    logger.info("Polling real training reports; press Ctrl-C to stop")
    while True:
        try:
            report = _get_recommendation(options.base_url, options.request_timeout)
            if report.get("status") == "empty":
                time.sleep(options.poll_interval)
                continue
            report_version = report.get("report_version")
            if isinstance(report_version, bool) or not isinstance(report_version, int):
                raise AutoscalerError(
                    f"Scaling report has no integer report_version: {report!r}"
                )
            status = _get_status(options.base_url, options.request_timeout)
            desired = status.get("desired_instances")
            stable, detail = _validate_stable_status(
                status, desired, require_proxy=options.require_proxy
            )
            decision = policy.evaluate(
                report,
                status,
                capacity_stable=stable,
                stability_detail=detail,
                now=time.monotonic(),
            )
            if decision.action != "ignore":
                logger.info(
                    "Autoscaler %s report version=%s: %s",
                    decision.action,
                    report.get("report_version"),
                    decision.message,
                )
            if decision.should_apply:
                changed = _apply_report(
                    options.base_url,
                    report,
                    request_timeout=options.request_timeout,
                    convergence_timeout=options.convergence_timeout,
                    poll_interval=options.poll_interval,
                    dry_run=options.dry_run,
                    require_proxy=options.require_proxy,
                )
                if changed:
                    converged = _get_status(options.base_url, options.request_timeout)
                    policy.record_convergence(
                        converged,
                        now=time.monotonic(),
                        action_direction=decision.direction,
                    )
            time.sleep(options.poll_interval)
        except requests.RequestException as exc:
            logger.warning("HTTP request failed: %s", exc)
            time.sleep(options.poll_interval)


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--base-url",
        required=True,
        help="RolloutController callback URL, for example http://127.0.0.1:18080.",
    )
    parser.add_argument(
        "--inject-spike",
        action="store_true",
        help="Inject deterministic metrics and verify a finite 1 -> 2 -> 1 loop.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Read recommendations without changing desired state.",
    )
    parser.add_argument(
        "--require-proxy",
        action="store_true",
        help="Require every converged READY instance to own an initialized V1 proxy.",
    )
    parser.add_argument("--poll-interval", type=float, default=2.0)
    parser.add_argument(
        "--cooldown",
        type=float,
        default=None,
        help=(
            "Legacy cooldown applied to every capacity-change direction. When set, "
            "it overrides the direction-aware cooldown options."
        ),
    )
    parser.add_argument(
        "--scale-up-cooldown",
        type=float,
        default=0.0,
        help="Cooldown between consecutive scale-up actions (default: 0).",
    )
    parser.add_argument(
        "--scale-down-cooldown",
        type=float,
        default=30.0,
        help="Cooldown between consecutive scale-down actions (default: 30).",
    )
    parser.add_argument(
        "--direction-change-cooldown",
        type=float,
        default=30.0,
        help="Cooldown before reversing the previous scaling direction (default: 30).",
    )
    parser.add_argument(
        "--scale-down-windows",
        type=int,
        default=2,
        help=(
            "Consecutive valid scale-down windows required before removing "
            "one instance."
        ),
    )
    parser.add_argument("--request-timeout", type=float, default=300.0)
    parser.add_argument("--convergence-timeout", type=float, default=600.0)
    options = parser.parse_args()
    options.base_url = options.base_url.rstrip("/")
    for name in (
        "poll_interval",
        "request_timeout",
        "convergence_timeout",
    ):
        if getattr(options, name) <= 0:
            parser.error(f"--{name.replace('_', '-')} must be positive")
    if options.cooldown is not None and options.cooldown < 0:
        parser.error("--cooldown must be non-negative")
    for name in (
        "scale_up_cooldown",
        "scale_down_cooldown",
        "direction_change_cooldown",
    ):
        if getattr(options, name) < 0:
            parser.error(f"--{name.replace('_', '-')} must be non-negative")
    if options.scale_down_windows <= 0:
        parser.error("--scale-down-windows must be positive")
    return options


def main() -> None:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(name)s %(levelname)s: %(message)s",
    )
    options = _parse_args()
    if options.inject_spike:
        _run_injected_spike(options)
    else:
        try:
            _run_live_loop(options)
        except KeyboardInterrupt:
            logger.info("Autoscaler stopped")


if __name__ == "__main__":
    main()
