apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: areal-elastic-shared
  namespace: areal-elastic-validation
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
  storageClassName: ""
  volumeName: areal-elastic-shared-pv
